### ISSUE TITLE
Plugin failed in Obsidian v0.13.19

### ISSUE THREAD

**Issue by BillKerman** [xldenis/obsidian-latex#16]
After updating v0.13.19,  preamble.sty does not load. I've tried to reopen the vault, create a new vault or test in another computer. I don't see any log so I don't know what's going wrong.  Could you check it, please?

**Comment by xldenis** [comment]
I'll take a look, but since the way the plug-in works is by hacking around obsidians markdown engine that's not all that surprising.

**Comment by xldenis** [comment]
A quick glace shows that it seems obsidian has changed how `MathJax` is loaded. I'll need to see exactly what changed and how we can still hook in.

**Comment by xldenis** [comment]
```
var Fh = ih("/lib/mathjax/tex-chtml-full.js", {
            before: function() {
                window.MathJax = {
                    tex: {
                        inlineMath: [],
                        displayMath: [],
                        processEscapes: !1,
                        processEnvironments: !1,
                        processRefs: !1
                    },
                    startup: {
                        typeset: !1
                    },
                    options: {
                        renderActions: {
                            addMenu: [0, "", ""]
                        },
                        menuOptions: {
                            settings: {
                                renderer: "CHTML"
                            }
                        }
                    }
                },
                localStorage.removeItem("MathJax-Menu-Settings")
            }
        });
        function Oh() {
            return k(this, void 0, Promise, (function() {
                return C(this, (function(e) {
                    switch (e.label) {
                    case 0:
                        return [4, Fh.promise];
                    case 1:
                        return e.sent(),
                        [2]
                    }
                }
                ))
            }
            ))
        }
        function Ih(e, t) {
            return MathJax.tex2chtml(e, {
                display: t
            })
        }
```

the `ih` function loads a script by creating a `script` tag, and also allows you to run `before` and `after` triggers.

**Comment by xldenis** [comment]
Ah, it seems like `registerMarkdownPostProcessor` is no longer being called at all, which explains why the plugin no longer does anything. Can you confirm it worked in `.18`?

**Comment by BillKerman** [comment]
> Ah, it seems like `registerMarkdownPostProcessor` is no longer being called at all, which explains why the plugin no longer does anything. Can you confirm it worked in `.18`?

Yes, actually, it still works after upgrading. This happens after I change the preamble.sty.

**Comment by xldenis** [comment]
Oh, weird. I'm going to take a further look into it, but happy to hear it's working again.

**Comment by BillKerman** [comment]
> Oh, weird. I'm going to take a further look into it, but happy to hear it's working again.

It doesn't work after I modify preamble.sty, but still I think it's a problem caused by `.19`, I'll downgrade and check.

**Comment by BillKerman** [comment]
> > Oh, weird. I'm going to take a further look into it, but happy to hear it's working again.
> 
> It doesn't work after I modify preamble.sty, but still I think it's a problem caused by `.19`, I'll downgrade and check.

Works fine under the old editor mode.

**Comment by xldenis** [comment]
> It doesn't work after I modify preamble.sty, but still I think it's a problem caused by .19, I'll downgrade and check.

Right, sorry. 

> Works fine under the old editor mode.

ie: it doesn't work with live preview?

I'll need to look into how that mechanism works.

**Comment by BillKerman** [comment]
> > It doesn't work after I modify preamble.sty, but still I think it's a problem caused by .19, I'll downgrade and check.
> 
> Right, sorry.
> 
> > Works fine under the old editor mode.
> 
> ie: it doesn't work with live preview?
> 
> I'll need to look into how that mechanism works.

Yes, the problem occurs after the release of the live preview. Thanks for your work!

**Comment by xldenis** [comment]
I believe this should be fixed now
