### ISSUE TITLE
Doesn't work on Obsidian mobile.

### ISSUE THREAD

**Issue by Bahnschrift** [xldenis/obsidian-latex#18]
It doesn't seem that the plugin works at all on Obsidian mobile. I'm using the same preamble.sty on desktop and mobile which works on desktop, but on mobile none of the commands are loaded.

**Comment by Bahnschrift** [comment]
My bad, I somehow managed to get it to work on my desktop with `Preamble.sty` instead of `preamble.sty`, which when I transferred it to my phone didn't work at all. Changed the P to lowercase and now it works on both.

**Comment by xldenis** [comment]
What filesystem are you using on your desktop? Sounds like you could be on a case-insensitive desktop (windows)

**Comment by Bahnschrift** [comment]
Yeah, I was syncing a notebook using git between my desktop (windows), iphone, and my laptop (linux). When it didn't work on my phone I incorrectly assumed there was a problem with the plugin on mobile since it's quite a different environment, but when it didn't work on my laptop too, I realised that I must be doing something wrong.

**Comment by michael-byrd** [comment]
I'm having issues with mobile. I am using Apple everything and my vault is stored in my iCloud. I have checked the file and everything works great on my computers, just not my phone.
