### ISSUE TITLE
preamble.sty not loading on start; but loads on toggling safe mode

### ISSUE THREAD

**Issue by tyjyang** [xldenis/obsidian-latex#19]
Hi I am on obsidian Desktop v0.14.2, and `preamble.sty` doesn't load on start.

What would make it work is if I turn on safe mode, and then turn it off. At this point all my custom latex commands would work again. However, if I then close obsidian and re-open it, those commands would be in red again.

I think this is symptomatic of errors on a deep level, could you help me with this? Thanks!

**Comment by xldenis** [comment]
Hmm, could you check the console for any error messages?

**Comment by MinusGix** [comment]
If you go to a line with red latex and then insert a character then remove it (to force it to refresh the rendering), does it work? If it does, then it might be that it renders it before it loads the plugin.

**Comment by tyjyang** [comment]
>

**Comment by tyjyang** [comment]
Hi guys, thanks for the replies, and sorry for not getting back to you earlier, some mishap in my email notifications. 

Indeed, there is some error message from the console:
![image](https://user-images.githubusercontent.com/23271252/162782915-6d499687-e26c-4e61-9cff-48352606c321.png)

And I checked @MinusGix 's suggestion, edit & re-render doesn't solve the issue.

**Comment by xldenis** [comment]
Oh fun... `amsmath` is missing? Do you think you could try re-installing obsidian?

**Comment by tyjyang** [comment]
Hi @xldenis , I tried to reinstall obsidian, now the version is `v0.14.5`, but the symptom persists, and I checked the console, it is indeed the same error:
![image](https://user-images.githubusercontent.com/23271252/162841294-99512b93-8d8c-4b74-9608-df5b8bf6d43c.png)

**Comment by tyjyang** [comment]
I found that this symptom is consistent throughout my Windows desktop, iPad, and iPhone.

**Comment by jonathanbeardsley** [comment]
I'm also (sort of) having the same problem, in that it's simply not loading. Toggling safe mode and reinstalling Obsidian don't seem to work. Using v 0.14.15 on a Mac. Has it simply stopped working because of an update or anything? I've also tried it with the legacy editor.

**Comment by xldenis** [comment]
If someone would like to take this plugin over I will happily give it. I don't enjoy attempting to follow Obsidian's API changes which break the hack which enables this.

**Comment by MinusGix** [comment]
The extension still works for me on 0.14.15 on Linux, so I wonder if there's some differences between platforms.
