### ISSUE TITLE
Where is the preamble file? I can`t find in the root of my vault.

### ISSUE THREAD

**Issue by GuangDai** [xldenis/obsidian-latex#2]
<div align=center><img src="https://gitee.com/guangdai/lpic/raw/master/img/20201223160253.png"/></div>

**Comment by xldenis** [comment]
You must create one yourself. I haven't been able to figure out how to make Obsidian see the file internally yet so you you'll have to edit it in a standalone editor.

**Comment by CNOT** [comment]
On a similar issue, it would be nice if the README file included an MWE and the steps required to get it going.

**Comment by xldenis** [comment]
Sure!

**Comment by xldenis** [comment]
I've added a MWE example that uses `bussproofs` + a custom macro in the preamble.
