### ISSUE TITLE
Cannot load LaTeX packages into preamble.sty

### ISSUE THREAD

**Issue by DylanJVA** [xldenis/obsidian-latex#20]
I'm trying to use the physics package and i tried including this in the preamble.sty:
`\usepackage{physics}`
 and I also tried this:
`\require{physics}`, which was according to [this obsidian forum post](https://forum.obsidian.md/t/a-textbox-in-the-settings-used-to-enable-physics-package-the-mathjax-extension-that-redefines-some-commands/4220/2).
The example you give does not show how to include some LaTeX package, it only shows how to define a macro. Unless thats not what this extensions can do, can you please explain how to use this extension to use an arbitrary LaTeX package?

**Comment by xldenis** [comment]
You cannot, Obsidian uses MathJax which while similar to latex is not latex.

**Comment by Leedehai** [comment]
Hi @xldenis it appears your answer contradicts with what you mentioned in https://forum.obsidian.md/t/new-plugin-mathjax-extended-preamble/10174 about using \require{...} wondering if I missed anything?

**Comment by wei2912** [comment]
> Update: Oddly enough, with preamble.sty like this
> 
> ```
> % Enable MathJax's "physics" package, which partially implements the LaTeX
> % package "physics".
> \require{physics}
> ```
> 
> I am indeed able to use the `physics` package in Obsidian, e.g. the differentials and partial derivatives render perfectly for me:
> 
> ```
> \dd x, \dd[2]x, \pdv[2]{f}{x}, \pdv{}{x}{y}
> ```
> 
> <img alt="Screenshot 2023-01-15 at 15 13 18" width="584" src="https://user-images.githubusercontent.com/18319900/212564631-b94c8bcb-5280-4368-af9a-e9357d504d98.png">

Sflr, please see https://docs.mathjax.org/en/latest/input/tex/extensions/physics.html - you can load the physics package dynamically under MathJax but it might not correspond entirely to the LaTeX `physics` package (not sure what the exact differences are).

**Comment by DylanJVA** [comment]
> Hi @xldenis it appears your answer contradicts with what you mentioned in https://forum.obsidian.md/t/new-plugin-mathjax-extended-preamble/10174 about using \require{physics}.
> 
> Wondering if I missed anything? Thanks 😊
> 
> Update: Oddly enough, with preamble.sty like this
> 
> ```
> % Enable MathJax's "physics" package, which partially implements the LaTeX
> % package "physics".
> \require{physics}
> ```
> 
> I am indeed able to use the `physics` package in Obsidian, e.g. the differentials and partial derivatives render perfectly for me:
> 
> ```
> \dd x, \dd[2]x, \pdv[2]{f}{x}, \pdv{}{x}{y}
> ```
> 
> <img alt="Screenshot 2023-01-15 at 15 13 18" width="584" src="https://user-images.githubusercontent.com/18319900/212564631-b94c8bcb-5280-4368-af9a-e9357d504d98.png">

Can confirm this works. Thank you! Not sure if it was added in the update...
