### ISSUE TITLE
Loading mhchem and bussproofs 

### ISSUE THREAD

**Issue by whitenoisedev** [xldenis/obsidian-latex#4]
Hi Xavier ,

I was wondering why you explicitly loading mhchem and bussproofs.
Aren't they bundled with Obsidian (mathjax-full) and autoloaded on first use?

**Comment by xldenis** [comment]
Huh, that may be the case, when I had originally developed the plugin I had tried to use `bussproofs` and got an error. If I can remove them then all the better :)
