### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by J-MR-T** [xldenis/obsidian-latex#8]
If I try to update the plugin or install it in a new vault via the plugin browser I get the mesage "Failed to isntall Plugin 'Extended MathJax'"

**Comment by joethei** [comment]
From what I can tell Obsidian tries to load the files for release 1.0.1 which does not exist.
Also the manifest, versions.json and the releases are out of sync.

**Comment by xldenis** [comment]
Yes, I there should be a new version on master that is unreleased.

**Comment by xldenis** [comment]
Ok that's incredibly thoughtless on my behalf. I had forgotten that obsidian pulled the `manifest.json` from master and had pushed an updated one in preparation for a new release.

**Comment by xldenis** [comment]
I've restored the previous one.
